name: Test on Kubernetes 1.27 and 1.32

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test-k8s:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        k8s-version: [1.30.0, 1.31.0]
    steps:
    - name: Kubernetes KinD Cluster
        uses: helm/kind-action@v1
        with:
          node_image: kindest/node:v${{ matrix.k8s-version }}
      # with:
      #   version: ${{ matrix.k8s-version }}
    - name: Verify Kind
      run: |
        kind -v

        