name: Test on Kubernetes 1.27 and 1.32

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test-k8s:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        k8s-version: [1.27.0, 1.32.0]
    steps:
    - name: Set up Kind
      uses: helm/kind-action@v1.2
      with:
        version: ${{ matrix.k8s-version }}
    - name: Verify Kind
      run: |
        kind -v

        