name: Test on Kubernetes 1.27 and 1.32

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test-k8s:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        k8s-version: [1.27.0, 1.32.0]

    steps:
    - name: Set up Kind
      uses: helm/kind-action@v1
      with:
        wait: 1m
        version: ${{ matrix.k8s-version }}

    - name: Verify Kind Installation
      run: kind --version

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.3'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      with:
        path: src/github.com/${{ github.repository }}
        fetch-depth: 0

    - name: Run go mod tidy
      run: |
        cd src/github.com/${{ github.repository }}
        go mod tidy

    - name: Run Tests
      run: |
        set -e -x

        export GOPATH=$(pwd)
        cd src/github.com/${{ github.repository }}

        # Install ytt for build
        mkdir -p /tmp/bin
        export PATH=/tmp/bin:$PATH

        ./hack/verify-no-dirty-files.sh

        wget -O- https://carvel.dev/install.sh | K14SIO_INSTALL_BIN_DIR=/tmp/bin bash

        # Ensure that there is no existing kapp installed
        rm -f /tmp/bin/kapp

        ./hack/build-binaries.sh

        export KAPP_E2E_NAMESPACE=kapp-test
        kubectl create ns $KAPP_E2E_NAMESPACE

        ./hack/test-all.sh